export const USERS = 
 [
  {
    userId: "user1234",
    userPw: "123123123a@",
    userPhoneNumber: "010-1234-5678",
    address: "서울 어딘가",
    favoritPlayer: "최승구",
    selectedJob: "회사원(사무직/연구직)",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user5678",
    userPw: "123123123a@",
    userPhoneNumber: "010-2345-6189",
    address: "부산 어딘가",
    favoritPlayer: "최우진",
    selectedJob: "대학생(대학원생 포함)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user9012",
    userPw: "123123123a@",
    userPhoneNumber: "010-3456-7800",
    address: "인천 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "프리랜서",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user3456",
    userPw: "123123123a@",
    userPhoneNumber: "010-4567-8801",
    address: "광주 어딘가",
    favoritPlayer: "박진홍",
    selectedJob: "서비스업 종사자",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user7890",
    userPw: "123123123a@",
    userPhoneNumber: "010-5678-9712",
    address: "대구 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "공무원",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user6789",
    userPw: "123123123a@",
    userPhoneNumber: "010-6789-0122",
    address: "울산 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "회사원(제조/건설/기술직)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user432",
    userPw: "123123123a@",
    userPhoneNumber: "010-7890-1204",
    address: "제주 어딘가",
    favoritPlayer: "백민규",
    selectedJob: "전업주부",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user765",
    userPw: "123123123a@",
    userPhoneNumber: "010-8201-2345",
    address: "대전 어딘가",
    favoritPlayer: "지언학",
    selectedJob: "법률 종사자",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user3422",
    userPw: "123123123a@",
    userPhoneNumber: "010-9052-3456",
    address: "강릉 어딘가",
    favoritPlayer: "김민석",
    selectedJob: "자영업자",
    singleOrMarried: "single",
    advertisement: "disagreement"
  },
  {
    userId: "user793",
    userPw: "123123123a@",
    userPhoneNumber: "010-0173-4567",
    address: "포항 어딘가",
    favoritPlayer: "무고사",
    selectedJob: "학생(초/중/고)",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user134",
    userPw: "123123123a@",
    userPhoneNumber: "010-1234-5670",
    address: "서울 어딘가",
    favoritPlayer: "무고사",
    selectedJob: "회사원(사무직/연구직)",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user6788",
    userPw: "123123123a@",
    userPhoneNumber: "010-2345-6789",
    address: "부산 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "대학생(대학원생 포함)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user012",
    userPw: "123123123a@",
    userPhoneNumber: "010-3456-7890",
    address: "부산 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "프리랜서",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user356",
    userPw: "123123123a@",
    userPhoneNumber: "010-4567-8901",
    address: "광주 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "서비스업 종사자",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user780",
    userPw: "123123123a@",
    userPhoneNumber: "010-5678-9012",
    address: "서울 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "공무원",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user689",
    userPw: "123123123a@",
    userPhoneNumber: "010-6789-0123",
    address: "울산 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "회사원(제조/건설/기술직)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user431",
    userPw: "123123123a@",
    userPhoneNumber: "010-7890-1234",
    address: "제주 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "전업주부",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user875",
    userPw: "123123123a@",
    userPhoneNumber: "010-8901-2345",
    address: "서울 어딘가",
    favoritPlayer: "지언학",
    selectedJob: "법률 종사자",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user341f2",
    userPw: "123123123a@",
    userPhoneNumber: "010-9012-3456",
    address: "강릉 어딘가",
    favoritPlayer: "김민석",
    selectedJob: "자영업자",
    singleOrMarried: "single",
    advertisement: "disagreement"
  },
  {
    userId: "user783",
    userPw: "123123123a@",
    userPhoneNumber: "010-0123-4567",
    address: "포항 어딘가",
    favoritPlayer: "최우진",
    selectedJob: "학생(초/중/고)",
    singleOrMarried: "married",
    advertisement: "agreement"
  }
]


export const POST = {
  announcement: [
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 }
  ],
  news: [
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 }
  ],
  utdReporter: [
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 23 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 54 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 68 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8874 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 19 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 }
  ],
  cheeringGrounds: [
    { type: "cheeringGrounds", author: "감동이", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 25 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 231 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 80 }
  ]
};


export const ADMIN = [
  { adminId : 'sonhanje',
    adminPw : '123123123a@'
  }
]