export const USERS = [
  {
    userId: '손감동손가락123',
    userPw: '123123123a@',
    userPhoneNumber: '010-1234-1234',
    address: '우주어딘가',
    favoritPlayer: '손흥민',
    selectedJob: '백수',
    singleOrMarried:'single',
    advertisement:'agreement'
  },
  {
    userId: '감동이발가락123',
    userPw: '123123123a@',
    userPhoneNumber: '010-5555-1234',
    address: '우주어딘가',
    favoritPlayer: '박지성',
    selectedJob: '백수',
    singleOrMarried:'single',
    advertisement:'agreement'
  },
  {
    userId: '똥개엉덩이1234',
    userPw: '123123123a@',
    userPhoneNumber: '010-7777-1234',
    address: '우주어딘가',
    favoritPlayer: '손흥민',
    selectedJob: '백수',
    singleOrMarried:'single',
    advertisement:'agreement'
  },
]

export const POST = {
  announcement: [
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 }
  ],
  news: [
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 }
  ],
  utdReporter: [
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 23 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 54 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 68 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8874 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 19 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 }
  ],
  cheeringGrounds: [
    { type: "cheeringGrounds", author: "감동이", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 25 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 231 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 80 }
  ]
};


export const ADMIN = [
  { adminId : 'sonhanje',
    adminPw : '123123123a@'
  }
]