export const USERS = 
 [
  {
    userId: "user1234",
    userPw: "123123123a@",
    userPhoneNumber: "010-1234-5678",
    address: "서울 어딘가",
    favoritPlayer: "최승구",
    selectedJob: "회사원(사무직/연구직)",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user5678",
    userPw: "123123123a@",
    userPhoneNumber: "010-2345-6189",
    address: "부산 어딘가",
    favoritPlayer: "최우진",
    selectedJob: "대학생(대학원생 포함)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user9012",
    userPw: "123123123a@",
    userPhoneNumber: "010-3456-7800",
    address: "인천 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "프리랜서",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user3456",
    userPw: "123123123a@",
    userPhoneNumber: "010-4567-8801",
    address: "광주 어딘가",
    favoritPlayer: "박진홍",
    selectedJob: "서비스업 종사자",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user7890",
    userPw: "123123123a@",
    userPhoneNumber: "010-5678-9712",
    address: "대구 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "공무원",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user6789",
    userPw: "123123123a@",
    userPhoneNumber: "010-6789-0122",
    address: "울산 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "회사원(제조/건설/기술직)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user432",
    userPw: "123123123a@",
    userPhoneNumber: "010-7890-1204",
    address: "제주 어딘가",
    favoritPlayer: "백민규",
    selectedJob: "전업주부",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user765",
    userPw: "123123123a@",
    userPhoneNumber: "010-8201-2345",
    address: "대전 어딘가",
    favoritPlayer: "지언학",
    selectedJob: "법률 종사자",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user3422",
    userPw: "123123123a@",
    userPhoneNumber: "010-9052-3456",
    address: "강릉 어딘가",
    favoritPlayer: "김민석",
    selectedJob: "자영업자",
    singleOrMarried: "single",
    advertisement: "disagreement"
  },
  {
    userId: "user793",
    userPw: "123123123a@",
    userPhoneNumber: "010-0173-4567",
    address: "포항 어딘가",
    favoritPlayer: "무고사",
    selectedJob: "학생(초/중/고)",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user134",
    userPw: "123123123a@",
    userPhoneNumber: "010-1234-5670",
    address: "서울 어딘가",
    favoritPlayer: "무고사",
    selectedJob: "회사원(사무직/연구직)",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user6788",
    userPw: "123123123a@",
    userPhoneNumber: "010-2345-6789",
    address: "부산 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "대학생(대학원생 포함)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user012",
    userPw: "123123123a@",
    userPhoneNumber: "010-3456-7890",
    address: "부산 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "프리랜서",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user356",
    userPw: "123123123a@",
    userPhoneNumber: "010-4567-8901",
    address: "광주 어딘가",
    favoritPlayer: "김현서",
    selectedJob: "서비스업 종사자",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user780",
    userPw: "123123123a@",
    userPhoneNumber: "010-5678-9012",
    address: "서울 어딘가",
    favoritPlayer: "음포쿠",
    selectedJob: "공무원",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user689",
    userPw: "123123123a@",
    userPhoneNumber: "010-6789-0123",
    address: "울산 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "회사원(제조/건설/기술직)",
    singleOrMarried: "married",
    advertisement: "disagreement"
  },
  {
    userId: "user431",
    userPw: "123123123a@",
    userPhoneNumber: "010-7890-1234",
    address: "제주 어딘가",
    favoritPlayer: "송시우",
    selectedJob: "전업주부",
    singleOrMarried: "single",
    advertisement: "agreement"
  },
  {
    userId: "user875",
    userPw: "123123123a@",
    userPhoneNumber: "010-8901-2345",
    address: "서울 어딘가",
    favoritPlayer: "지언학",
    selectedJob: "법률 종사자",
    singleOrMarried: "married",
    advertisement: "agreement"
  },
  {
    userId: "user341f2",
    userPw: "123123123a@",
    userPhoneNumber: "010-9012-3456",
    address: "강릉 어딘가",
    favoritPlayer: "김민석",
    selectedJob: "자영업자",
    singleOrMarried: "single",
    advertisement: "disagreement"
  },
  {
    userId: "user783",
    userPw: "123123123a@",
    userPhoneNumber: "010-0123-4567",
    address: "포항 어딘가",
    favoritPlayer: "최우진",
    selectedJob: "학생(초/중/고)",
    singleOrMarried: "married",
    advertisement: "agreement"
  }
]


export const POST = {
  announcement: [
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1512 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 52 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 79 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 96 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "notice", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 32 }
  ],
  news: [
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 20 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 50 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 48 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "news", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 84 }
  ],
  utdReporter: [
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 23 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 51 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 54 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 1 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 68 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 8874 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 847 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 65 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 18 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 19 },
    { type: "report", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 }
  ],
  cheeringGrounds: [
    { type: "cheeringGrounds", author: "감동이", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 0 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 12 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 25 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 385 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 98 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 41 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 851 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 5 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 78 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 4 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 841 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 21 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 231 },
    { type: "cheeringGrounds", author: "감동이똥구멍", title: "인천유나이티드 직원(그라운드 관리) 채용 공고", views: 80 }
  ]
};


export const ADMIN = [
  { adminId : 'sonhanje',
    adminPw : '123123123a@'
  }
]


export const PLAYERS = [
  { position : "골키퍼", type : "선수", backNumber :"1", name:"민성준",englishName: "MIN SEONG JUN"},
  { position : "골키퍼", type : "선수", backNumber :"25", name:"이범수",englishName:"LEE BUM SOO"},
  { position : "골키퍼", type : "선수", backNumber :"29", name:"김유성",englishName:"KIM YU SUNG"},
  { position : "골키퍼", type : "선수", backNumber :"31", name:"성윤수",englishName:"SUNG YOON SOO"},
  { position : "수비수", type : "선수", backNumber : "2" ,name : "김건희", englishName:"KIM GEON HUI"},
  { position : "수비수", type : "선수", backNumber : "3" ,name : "김연수", englishName:"KIM YEON SOO"},
  { position : "수비수", type : "선수", backNumber : "4" ,name : "오반석", englishName:"OH BAN SUK"},
  { position : "수비수", type : "선수", backNumber : "13" ,name : "최승구", englishName:"CHOI SEUNG GU"},
  { position : "수비수", type : "선수", backNumber : "14" ,name : "최우진", englishName:"CHOI WOO JIN"},
  { position : "수비수", type : "선수", backNumber : "15" ,name : "임형진", englishName:"LIM HYEONG JIN"},
  { position : "수비수", type : "선수", backNumber : "17" ,name : "김준엽", englishName:"KIM JUN YUB"},
  { position : "수비수", type : "선수", backNumber : "20" ,name : "델브리지", englishName:"DELBRIDGE HARRISON ANDREW"},
  { position : "수비수", type : "선수", backNumber : "23" ,name : "정동윤", englishName:"JUNG DONG YOON"},
  { position : "수비수", type : "선수", backNumber : "26" ,name : "김성민", englishName:"KIM SEONG MIN"},
  { position : "수비수", type : "선수", backNumber : "28" ,name : "민경현", englishName:"MIN GYEONG HYEON"},
  { position : "수비수", type : "선수", backNumber : "37" ,name : "홍시후", englishName:"HONG SI HOO"},
  { position : "수비수", type : "선수", backNumber : "47" ,name : "김동민", englishName:"KIM DONG MIN"},
  { position : "수비수", type : "선수", backNumber : "55" ,name : "권한진", englishName:"KWON HAN JIN"},
  { position : "수비수", type : "선수", backNumber : "82" ,name : "요니치", englishName:"MATEJ JONJIC"},
  { position : "미드필더", type : "선수", backNumber : "5",  name :"이명주", englishName :"LEE MYUNG JOO"},
  { position : "미드필더", type : "선수", backNumber : "6",  name :"문지환", englishName :"MUN JI HWAN"},
  { position : "미드필더", type : "선수", backNumber : "7",  name :"김도혁", englishName :"KIM DO HYEOK"},
  { position : "미드필더", type : "선수", backNumber : "8",  name :"신진호", englishName :"SHIN JIN HO"},
  { position : "미드필더", type : "선수", backNumber : "16", name :"이가람", englishName :"LEE GA RAM"},
  { position : "미드필더", type : "선수", backNumber : "30", name :"김훈", englishName :"KIM HUN"},
  { position : "미드필더", type : "선수", backNumber : "32", name :"강도욱", englishName :"KANG DO UK"},
  { position : "미드필더", type : "선수", backNumber : "33", name :"김현서", englishName :"KIM HYUN SEO"},
  { position : "미드필더", type : "선수", backNumber : "38", name :"박진홍", englishName :"PARK JIN HONG"},
  { position : "미드필더", type : "선수", backNumber : "40", name :"음포쿠", englishName :"PAUL JOSE MPOKU"},
  { position : "공격수", type : "선수", backNumber : "11",name :"제르소",englishName :"FERNANDES GERSO"},
  { position : "공격수", type : "선수", backNumber : "9", name :"무고사", englishName:"MUGOSA STEFAN"},
  { position : "공격수", type : "선수", backNumber : "19",name :"송시우",englishName :"SONG SI WOO"},
  { position : "공격수", type : "선수", backNumber : "21",name :"백민규",englishName :"BAEK MIN GYU"},
  { position : "공격수", type : "선수", backNumber : "22",name :"지언학",englishName :"JI EON HAK"},
  { position : "공격수", type : "선수", backNumber : "24",name :"김민석",englishName :"KIM MIN SEOK"},
  { position : "공격수", type : "선수", backNumber : "27",name :"김보섭",englishName :"KIM BO SUB"},
  { position : "공격수", type : "선수", backNumber : "34",name :"하동선",englishName :"HA DONG SEON"},
  { position : "공격수", type : "선수", backNumber : "66",name :"김세훈",englishName :"KIM SE HOON"},
  { position : "공격수", type : "선수", backNumber : "77",name :"박승호",englishName :"PARK SEUNG HO"},
  { position : "공격수", type : "선수", backNumber : "88",name :"이종욱",englishName :"LEE JONG UK"},
  { type :"군입대", name:"김동현"},
  { type :"군입대", name:"강윤구"},
  { type :"군입대", name:"이태희"},
  { type :"우선지명", name : "신동욱",currentTeam:"DF/광운대"},
  { type :"우선지명", name : "진현준",currentTeam:"DF/평택시티즌K4"},
  { type :"우선지명", name : "조은준",currentTeam:"FW/동국대"},
  { type :"우선지명", name : "한동훈",currentTeam:"DF/여주대"},
  { type :"우선지명", name : "안현희",currentTeam:"MF/동명대"},
  { type :"우선지명", name : "김현서",currentTeam:"DF/동국대"},
  { type :"우선지명", name : "박경섭",currentTeam:"DF/선문대"},
  { type :"우선지명", name : "이충원",currentTeam:"GK/안동과학대"},
  { type :"우선지명", name : "강민성",currentTeam:"FW/ 인천대"},
  { type :"우선지명", name : "윤재원",currentTeam:"MF/청주대"}
,]